"""preprocess_images.py — DICOM -> CONTRALATERAL-knee 512x512 crop -> WebDataset shards.

Track C of the plan, torch-free. This module turns each pre-index radiograph of the
LOCKED 3,709-patient cohort into one 8-bit PNG that contains the CONTRALATERAL knee
(the knee that has NOT been replaced) and nothing else, then packs those PNGs into
WebDataset-compatible `.tar` shards with a per-image label sidecar.

Success non-negotiable #1 (protocol sections 14/23): the crop must contain the
contralateral knee, ZERO index-knee pixels, and ZERO burned-in laterality markers.
4,075 of the 4,269 frontal films are bilateral ('B' — BOTH knees on one image), so a
metadata-guided half-select is required and an inverted sign convention there would
silently train the model on the already-replaced knee. `contralateral_image_half`
is therefore written as a small pure function with the truth table in its docstring,
covered by tests/test_preprocess_images.py, and audited visually by src/crop_qa.py,
which BLOCKS training until a reviewer signs off.

Non-negotiable #2 (no leakage): intensity normalization is strictly PER IMAGE
(robust percentile clip + min-max). No statistic is pooled across images, so no
cross-split quantity exists to leak and none is persisted.

Non-negotiable #4 (sealed test): `--splits` defaults to `train,val`. Processing the
test split additionally requires the explicit `--include-test` flag and is logged
at WARNING level.

Protocol section 13 (masked pixels): every crop records `masked_pct` — the border band
that `mask_borders` unconditionally destroys PLUS the out-of-bounds padding that
`square_crop` had to invent — and a crop whose `masked_pct` exceeds
`preprocess.max_masked_pct`, or whose joint localization FAILED, is routed to the
failure report instead of into a shard. Nothing that a reviewer would call "mostly
blank" or "not actually localized" reaches the model.

Manifest composition (verified against the parquet on 2026-07-24; asserted in
`build_manifest`, so a silent upstream change fails loudly):
  6,122 selected images -> 6,090 kept after dropping 32 'E'/'I' rows (config views_kept)
  frontal 'F' 4,269 = 4,075 bilateral 'B' (half-select) + 194 unilateral
  lateral 'L' 1,659 + sunrise 'S' 162  -> already contralateral-side-only, no half-select
  horizontal_flip == 1 on 287 kept images; inverted == 1 on 1,476 kept images
  3,709 patients; kept rows by split: train 4,270 / val 602 / test 1,218

KNOWN LIMITATION — the two MRKR flags this module trusts are NOT equally trustworthy:
  * `inverted` is CROSS-CHECKED. Every decode reads the DICOM's own
    PhotometricInterpretation tag, and disagreements with the manifest flag are counted
    (`n_inverted_disagree` in preprocess_run.json). The DICOM tag wins; the manifest
    flag is reported only. A wrong `inverted` flag therefore cannot corrupt a crop.
  * `horizontal_flip` is NOT cross-checked and CANNOT BE. It is a MODEL-INFERRED MRKR
    annotation (generated by models trained on 6,000 annotated images, dataset caution
    B.4) with an UNQUANTIFIED error rate, and no DICOM tag records it. It drives
    half-select on 287 bilateral films: a false positive or false negative there hands
    the model the INDEX knee for that image. There is no automated defence — this is
    precisely why src.crop_qa renders the full film with the selected half outlined and
    blocks training until a human confirms the half-select on a real sample.

This module DEFINES THE CONTRACT that notebooks/preprocess_colab.ipynb (task T5) must
mirror byte-for-byte and that notebooks/train_colab.ipynb (task T7) reads. The public
functions below are the contract: keep them small, pure, and identically named.

Run:  python3 -m src.preprocess_images --dicom-root <DICOM root> --out-dir <shard dir>
      python3 -m src.preprocess_images --dicom-root <DICOM root> --dry-run
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import logging
import sys
import tarfile
import time
from dataclasses import dataclass, asdict
from pathlib import Path

import numpy as np
import pandas as pd
import scipy.ndimage as ndi
from PIL import Image

from src.config import PROJECT_ROOT, load_config

MODULE = "preprocess_images"

# WebDataset splits a member name on its FIRST dot, so a sample key must not contain
# one. empi_anon is numeric, view is alphabetic, and the uid short is hex -> safe.
KEY_TEMPLATE = "{empi_anon}_{view}_{uid_short}"
UID_SHORT_LEN = 12
PNG_COMPRESS_LEVEL = 6          # PIL default; pinned so T5 reproduces identical bytes
LOCALIZER_WORK_PX = 384         # localization runs on a downsampled copy (speed only)

# Failure reasons raised by the protocol-section-13 exclusion rules.
REASON_EXCESSIVE_MASKING = "excessive_masking"
REASON_LOCALIZATION_FAILED = "localization_failed"


def setup_logging(log_path: Path) -> logging.Logger:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    lg = logging.getLogger(MODULE)
    lg.setLevel(logging.INFO)
    lg.propagate = False
    if not any(getattr(h, "_mrkr", False) for h in lg.handlers):
        fh = logging.FileHandler(log_path, mode="a")   # run.log is shared + APPEND-ONLY
        fh._mrkr = True  # type: ignore[attr-defined]
        fh.setFormatter(logging.Formatter(
            f"{MODULE} | %(asctime)s | %(levelname)s | %(message)s", datefmt="%Y-%m-%dT%H:%M:%S"))
        lg.addHandler(fh)
        sh = logging.StreamHandler(sys.stdout)
        sh._mrkr = True  # type: ignore[attr-defined]
        sh.setFormatter(logging.Formatter(f"{MODULE} | %(levelname)s | %(message)s"))
        lg.addHandler(sh)
    return lg


# =============================================================================
# Parameters (every value comes from config `preprocess:` — nothing hard-coded)
# =============================================================================
@dataclass(frozen=True)
class PreprocessParams:
    """The frozen crop contract. T5's Colab notebook must construct this identically."""
    out_size: int
    apply_rescale: bool
    apply_voi_lut: bool
    monochrome1_invert: bool
    clip_percentiles: tuple[float, float]
    bilateral_display_convention: str
    apply_horizontal_flip_correction: bool
    half_inset_frac: float
    crop_margin_frac: float
    min_crop_frac: float
    max_crop_frac: float
    standardize_to_left: bool
    mask_border_frac: float
    localizer: str
    localizer_mode: str
    localizer_refine_min_confidence: float
    mask_markers: bool
    marker_sat_level: int
    marker_min_px: int
    marker_max_area_frac: float
    marker_ring_px: int
    marker_ring_max_level: int
    marker_merge_px: int
    image_format: str
    min_crop_confidence: float
    max_masked_pct: float
    exclude_failed_localization: bool

    @classmethod
    def from_config(cls, cfg) -> "PreprocessParams":
        p = cfg["preprocess"]
        lo, hi = p["clip_percentiles"]
        return cls(
            out_size=int(p["out_size"]),
            apply_rescale=bool(p["apply_rescale"]),
            apply_voi_lut=bool(p["apply_voi_lut"]),
            monochrome1_invert=bool(p["monochrome1_invert"]),
            clip_percentiles=(float(lo), float(hi)),
            bilateral_display_convention=str(p["bilateral_display_convention"]),
            apply_horizontal_flip_correction=bool(p["apply_horizontal_flip_correction"]),
            half_inset_frac=float(p["half_inset_frac"]),
            crop_margin_frac=float(p["crop_margin_frac"]),
            min_crop_frac=float(p["min_crop_frac"]),
            max_crop_frac=float(p["max_crop_frac"]),
            standardize_to_left=bool(p["standardize_to_left"]),
            mask_border_frac=float(p["mask_border_frac"]),
            localizer=str(p["localizer"]),
            localizer_mode=str(p.get("localizer_mode", "center_default")),
            localizer_refine_min_confidence=float(p.get("localizer_refine_min_confidence", 0.60)),
            mask_markers=bool(p.get("mask_markers", True)),
            marker_sat_level=int(p.get("marker_sat_level", 250)),
            marker_min_px=int(p.get("marker_min_px", 20)),
            marker_max_area_frac=float(p.get("marker_max_area_frac", 0.01)),
            marker_ring_px=int(p.get("marker_ring_px", 6)),
            marker_ring_max_level=int(p.get("marker_ring_max_level", 60)),
            marker_merge_px=int(p.get("marker_merge_px", 10)),
            image_format=str(p["shards"]["image_format"]),
            min_crop_confidence=float(p["min_crop_confidence"]),
            max_masked_pct=float(p["max_masked_pct"]),
            exclude_failed_localization=bool(p["exclude_failed_localization"]),
        )


@dataclass(frozen=True)
class Localization:
    """Output of any joint localizer. A learned detector in Colab must return THIS."""
    row: float
    col: float
    side: float
    confidence: float
    method: str


@dataclass(frozen=True)
class CropSpec:
    """Every geometric decision taken for one image (audited by src.crop_qa)."""
    view: str
    contra_side: str
    half_selected: str          # "left" | "right" | "none"
    orientation: str            # "left" | "right" — knee side as the crop READS
    mirrored: bool
    crop_method: str            # "intensity_profile" | "fallback_center"
    crop_confidence: float
    masked_pct: float           # protocol section 13: border band + out-of-bounds padding


class PreprocessError(RuntimeError):
    """Raised for a per-image failure that must be routed to the failure report."""

    def __init__(self, reason: str, detail: str = ""):
        super().__init__(f"{reason}: {detail}" if detail else reason)
        self.reason = reason
        self.detail = detail


# =============================================================================
# 1. DICOM decode
# =============================================================================
def _pixel_fns():
    """pydicom moved these helpers to pydicom.pixels in 3.x; support both locations."""
    try:
        from pydicom.pixels import apply_voi_lut, apply_modality_lut  # pydicom >= 3.0
    except Exception:                              # pragma: no cover - version fallback
        from pydicom.pixel_data_handlers.util import apply_voi_lut, apply_modality_lut
    return apply_voi_lut, apply_modality_lut


def read_dicom(path: str | Path, params: PreprocessParams) -> tuple[np.ndarray, dict]:
    """Decode one DICOM to a float32 2-D array in [0, 1] under the DISPLAY convention
    (higher value = brighter = denser bone).

    Order: pixel_array -> RescaleSlope/Intercept -> VOI LUT (window or LUT sequence)
    -> MONOCHROME1 inversion -> robust percentile clip -> min-max to [0, 1].

    The percentile clip is PER IMAGE. No statistic crosses image boundaries, so there
    is no cross-split calibration to leak (non-negotiable #2).

    Returns (array, meta) where meta carries PhotometricInterpretation, the
    `dicom_inverted` flag so the caller can cross-check the manifest `inverted` column,
    and `modality_lut_error` / `voi_lut_error`. Both LUT steps degrade rather than fail
    (a malformed LUT must not lose an otherwise usable image), but the degradation is
    NOT silent: the exception text is returned so the driver can count it and surface it
    in the run record instead of swallowing it.
    """
    import pydicom

    try:
        ds = pydicom.dcmread(str(path))
        arr = ds.pixel_array
    except Exception as exc:
        raise PreprocessError("decode_failed", f"{type(exc).__name__}: {exc}") from exc

    if arr.ndim == 3:
        arr = arr[arr.shape[0] // 2] if arr.shape[-1] not in (3, 4) else arr[..., 0]
    if arr.ndim != 2:
        raise PreprocessError("bad_shape", f"ndim={arr.ndim}")
    apply_voi, apply_modality = _pixel_fns()
    modality_lut_error = ""
    voi_lut_error = ""
    voi_lut_on_float = False

    # A VOI LUT *Sequence* is an INTEGER-INDEXED lookup table, so it should see the native
    # integer pixels; casting to float first makes pydicom warn "Applying a VOI LUT on a
    # float input array may give incorrect results".
    #
    # Scope, measured on real MRKR data (2026-07-25) — this is HARDENING, not a bug fix:
    # the modality transform is the IDENTITY in 100% of 300 sampled files (286 with
    # slope=1/intercept=0, 14 with no rescale tags, 0 ModalityLUTSequence) and 8% carry a
    # VOILUTSequence. Because an identity transform leaves the float values exactly integral,
    # the lookup landed on the same entries either way: old vs new output was bit-identical
    # on 8 VOILUTSequence images. Nothing was ever mis-decoded.
    #
    # It is kept because a non-integral RescaleSlope WOULD index the LUT wrongly and do so
    # silently. Staying integer when the transform is a no-op costs nothing; a genuinely
    # non-identity transform still forces float and is recorded in `voi_lut_on_float`.
    if params.apply_rescale and not _modality_is_identity(ds):
        try:
            arr = np.asarray(apply_modality(arr, ds), dtype=np.float32)
        except Exception as exc:
            modality_lut_error = f"{type(exc).__name__}: {exc}"
            slope = float(ds.get("RescaleSlope", 1.0) or 1.0)
            intercept = float(ds.get("RescaleIntercept", 0.0) or 0.0)
            arr = arr.astype(np.float32) * slope + intercept

    if params.apply_voi_lut:
        has_window = ds.get("WindowCenter", None) is not None and ds.get("WindowWidth", None) is not None
        has_lut = ds.get("VOILUTSequence", None) is not None
        if has_window or has_lut:
            voi_lut_on_float = bool(has_lut and np.issubdtype(arr.dtype, np.floating))
            try:
                arr = np.asarray(apply_voi(arr, ds), dtype=np.float32)
            except Exception as exc:
                # a malformed LUT must not lose the image; the rescaled pixels still train
                voi_lut_error = f"{type(exc).__name__}: {exc}"

    arr = np.asarray(arr, dtype=np.float32)

    photometric = str(getattr(ds, "PhotometricInterpretation", "") or "")
    dicom_inverted = photometric.upper() == "MONOCHROME1"
    if params.monochrome1_invert and dicom_inverted:
        arr = float(arr.max()) - arr

    arr = robust_scale(arr, params.clip_percentiles)
    meta = {
        "photometric": photometric,
        "dicom_inverted": bool(dicom_inverted),
        "rows": int(arr.shape[0]),
        "cols": int(arr.shape[1]),
        "modality_lut_error": modality_lut_error,
        "voi_lut_error": voi_lut_error,
        "voi_lut_on_float": bool(voi_lut_on_float),
    }
    return arr, meta


def _modality_is_identity(ds) -> bool:
    """True when the DICOM modality transform is a no-op, so the array can stay integer.

    Identity means: no ModalityLUTSequence, and RescaleSlope/Intercept are either absent or
    exactly (1, 0). Staying integer matters because a VOI LUT Sequence is indexed by pixel
    value (see read_dicom).
    """
    if ds.get("ModalityLUTSequence", None) is not None:
        return False
    slope = ds.get("RescaleSlope", None)
    intercept = ds.get("RescaleIntercept", None)
    slope_ok = slope is None or float(slope) == 1.0
    intercept_ok = intercept is None or float(intercept) == 0.0
    return bool(slope_ok and intercept_ok)


def robust_scale(arr: np.ndarray, clip_percentiles: tuple[float, float]) -> np.ndarray:
    """Per-image robust clip to [lo, hi] percentiles then min-max to [0, 1]."""
    lo_p, hi_p = clip_percentiles
    finite = np.isfinite(arr)
    if not finite.any():
        raise PreprocessError("degenerate_pixels", "no finite pixels")
    vals = arr[finite]
    lo = float(np.percentile(vals, lo_p))
    hi = float(np.percentile(vals, hi_p))
    if not np.isfinite(lo) or not np.isfinite(hi) or hi <= lo:
        lo, hi = float(vals.min()), float(vals.max())
    if hi <= lo:
        return np.zeros_like(arr, dtype=np.float32)
    out = (np.clip(np.nan_to_num(arr, nan=lo), lo, hi) - lo) / (hi - lo)
    return out.astype(np.float32)


# =============================================================================
# 2-3. Flip correction and the CRITICAL half-select
# =============================================================================
def apply_flip_correction(arr: np.ndarray, horizontal_flip: int, enabled: bool) -> tuple[np.ndarray, bool]:
    """Mirror left-right when the manifest says the stored pixels are flipped.

    After this returns True the array obeys `bilateral_display_convention` exactly,
    so `select_contralateral_half` must be called with flip_corrected=True.
    """
    if enabled and int(horizontal_flip or 0) == 1:
        return np.ascontiguousarray(arr[:, ::-1]), True
    return arr, False


def contralateral_image_half(contra_side: str, horizontal_flip: int,
                             convention: str = "radiological",
                             flip_corrected: bool = True) -> str:
    """Which HALF of the pixel array (by COLUMN index) holds the CONTRALATERAL knee.

    Returns "left"  -> low  column indices, arr[:, :mid]
            "right" -> high column indices, arr[:, mid:]

    SIGN CONVENTION, spelled out because inverting it silently trains the model on the
    INDEX (already-replaced) knee, the single worst failure mode in this study:

      convention == "radiological"  (config bilateral_display_convention):
          the patient's RIGHT side is displayed on the IMAGE LEFT.
              contra_side == "R"  ->  "left"
              contra_side == "L"  ->  "right"
      convention == "anatomical":
          the patient's RIGHT side is displayed on the IMAGE RIGHT; both rows swap.

    `horizontal_flip` (MRKR image.horizontal_flip == 1) means the STORED pixels are
    mirrored left-right relative to the convention above.
          flip_corrected is True  -> the caller already un-mirrored the array via
                                     apply_flip_correction, so the flag must NOT be
                                     applied a second time.
          flip_corrected is False -> the array is raw, so horizontal_flip == 1 SWAPS
                                     the answer.
    Either call style yields the same anatomical knee; that redundancy is deliberate.
    """
    contra_side = str(contra_side).upper()
    assert contra_side in ("L", "R"), f"contra_side must be L or R, got {contra_side!r}"
    convention = str(convention).lower()
    assert convention in ("radiological", "anatomical"), f"unknown convention {convention!r}"

    half = "left" if contra_side == "R" else "right"          # radiological base case
    if convention == "anatomical":
        half = "right" if half == "left" else "left"
    if not flip_corrected and int(horizontal_flip or 0) == 1:
        half = "right" if half == "left" else "left"
    return half


def half_column_bounds(width: int, half: str, inset_frac: float) -> tuple[int, int]:
    """Column slice [c0, c1) of the selected half of a `width`-wide bilateral film.

    Factored out of `select_contralateral_half` so src.crop_qa can draw the EXACT
    rectangle the pipeline sliced onto the full film — the QA overlay is derived from
    the same arithmetic as the crop, never re-derived by eye.
    """
    assert half in ("left", "right"), f"half must be left|right, got {half!r}"
    w = int(width)
    mid = w // 2
    inset = int(round(float(inset_frac) * w))
    if half == "left":
        return 0, max(1, mid - inset)
    return min(w - 1, mid + inset), w


def select_contralateral_half(arr: np.ndarray, contra_side: str, horizontal_flip: int,
                              convention: str = "radiological",
                              flip_corrected: bool = True,
                              inset_frac: float = 0.0) -> tuple[np.ndarray, str]:
    """Slice the half of a BILATERAL frontal film that holds the contralateral knee.

    `inset_frac` (config half_inset_frac) is a fraction of the FULL image width and
    moves the cut AWAY from the midline, INTO the selected half, so the midline strip
    — where index-knee pixels could survive a slightly off-centre patient — is
    discarded rather than kept. Selecting the left half returns columns
    [0, mid - inset); the right half returns columns [mid + inset, W).

    Returns (half_array, half_name) with half_name in {"left", "right"}.
    """
    assert arr.ndim == 2, f"expected 2-D array, got ndim={arr.ndim}"
    half = contralateral_image_half(contra_side, horizontal_flip, convention, flip_corrected)
    c0, c1 = half_column_bounds(arr.shape[1], half, inset_frac)
    out = arr[:, c0:c1]
    assert out.shape[1] >= 1, "half-select produced an empty slice"
    return np.ascontiguousarray(out), half


# =============================================================================
# 4. Joint localization (classical, explainable; config localizer)
# =============================================================================
def otsu_threshold(img: np.ndarray, nbins: int = 256) -> float:
    """Otsu's threshold on a [0, 1] image. Implemented here so the module stays
    dependency-light (scikit-image is not installable on this interpreter).

    Returns the UPPER edge of the winning bin, not its centre: for a perfectly bimodal
    image the between-class variance is a plateau and argmax lands on the bin holding
    the background mode, so `img > centre` would keep the background as foreground.
    """
    hist, edges = np.histogram(np.clip(img, 0.0, 1.0), bins=nbins, range=(0.0, 1.0))
    hist = hist.astype(np.float64)
    total = hist.sum()
    if total <= 0:
        return 0.5
    centers = 0.5 * (edges[:-1] + edges[1:])
    p = hist / total
    omega = np.cumsum(p)                 # class-0 probability mass up to and including bin i
    mu = np.cumsum(p * centers)          # first-order cumulative moment
    mu_t = mu[-1]
    valid = (omega > 0.0) & (omega < 1.0)
    between = np.zeros(nbins, dtype=np.float64)
    between[valid] = ((mu_t * omega[valid] - mu[valid]) ** 2) / (omega[valid] * (1.0 - omega[valid]))
    return float(edges[int(np.argmax(between)) + 1])


def _fallback_localization(shape: tuple[int, int], params: PreprocessParams) -> Localization:
    """Deterministic centred crop. Sized at max_crop_frac: when localization fails a
    crop that is too SMALL can cut the joint out entirely, while one that is too large
    only adds context, and the half-select already guarantees no index-knee pixels."""
    h, w = shape
    short = float(min(h, w))
    return Localization(row=h / 2.0, col=w / 2.0, side=params.max_crop_frac * short,
                        confidence=0.0, method="fallback_center")


def mask_burned_in_markers(u8: np.ndarray, params: PreprocessParams) -> tuple[np.ndarray, int, float]:
    """Blank burned-in laterality letters / positioning markers left inside the crop.

    Protocol section 13 requires burned-in text to be masked, and non-negotiable #1 requires
    ZERO laterality markers to survive. A fixed `mask_border_frac` band only removes what sits
    at the very edge: measured on 500 real TRAIN crops, **26.4%** still carried a marker inside
    the band (frontal 15.8%, lateral 52.7%, sunrise 50.0%) — 'L', 'R', mirrored 'Я', technologist
    initials, arrows, circular anode markers.

    These are lead markers laid on the cassette, so they are SATURATED, SMALL, and sit on
    unexposed background. That triple signature is what separates them from bone:

      1. saturated:  value >= `marker_sat_level`
      2. small:      area within [`marker_min_px`, `marker_max_area_frac` x image]
      3. isolated:   the dilated ring around the blob is mostly dark
                     (median <= `marker_ring_max_level`), i.e. it sits on background,
                     whereas saturated bone is surrounded by mid-grey soft tissue

    The largest saturated component is never masked — that is bone or a collimator edge.
    Each masked blob is filled with its own ring median, not with 0, so the operation does not
    stamp a hard black rectangle that is itself a learnable artifact.

    Returns `(masked_u8, n_blobs_masked, fraction_of_pixels_masked)`.
    """
    if not params.mask_markers:
        return u8, 0, 0.0
    hot = u8 >= params.marker_sat_level
    if not hot.any():
        return u8, 0, 0.0
    lab, n = ndi.label(hot)
    if n == 0:
        return u8, 0, 0.0
    area = float(u8.size)
    sizes = ndi.sum(hot, lab, range(1, n + 1))
    keep_largest = int(np.argmax(sizes)) + 1          # bone / collimator edge — never mask
    candidates = hot & (lab != keep_largest)
    if not candidates.any():
        return u8, 0, 0.0

    # Text is MULTI-GLYPH: 'L', 'R', 'CROSS-TABLE', technologist initials are each several
    # separate components. Handling them one at a time strips some glyphs and leaves others,
    # which is worse than doing nothing — a half-erased marker is still a learnable artifact
    # and now carries a synthetic fill patch too. So dilate first to merge neighbouring
    # glyphs into one text REGION, then accept or reject the region as a whole.
    merged = ndi.binary_dilation(candidates, iterations=params.marker_merge_px)
    mlab, mn = ndi.label(merged)
    out = u8.copy()
    masked_px = 0
    n_masked = 0
    for k in range(1, mn + 1):
        region = mlab == k
        ink = float((candidates & region).sum())      # saturated pixels actually in the region
        if ink < params.marker_min_px or ink > params.marker_max_area_frac * area:
            continue
        ring = ndi.binary_dilation(region, iterations=params.marker_ring_px) & ~region
        if not ring.any():
            continue
        ring_med = float(np.median(out[ring]))
        if ring_med > params.marker_ring_max_level:
            continue                                   # sits on tissue, not background -> anatomy
        out[region] = np.uint8(round(ring_med))
        masked_px += int(region.sum())
        n_masked += 1
    return out, n_masked, masked_px / area


def center_localization(shape: tuple[int, int], params: PreprocessParams) -> Localization:
    """The PRIMARY crop centre: a deterministic centred box (method 'center_default').

    Geometrically identical to `_fallback_localization`, but it means the opposite thing.
    The fallback is "localization failed, salvage something"; this is "the centred box is
    the chosen estimate". Radiographers centre the knee in the collimated field, so the
    image centre is a strong, unbiased prior — measured on 800 real TRAIN films it beats
    the intensity-profile localizer, which locks onto bright shafts and collimator edges
    and drags the box off the joint (see config `preprocess.localizer_mode`).

    Confidence is 1.0 because this estimate is exact by construction: it is not a guess
    about anatomy, it is a deliberate policy. Nothing is excluded for using it.
    """
    h, w = shape
    short = float(min(h, w))
    return Localization(row=h / 2.0, col=w / 2.0, side=params.max_crop_frac * short,
                        confidence=1.0, method="center_default")


def choose_localization(img: np.ndarray, params: PreprocessParams) -> tuple[Localization, Localization]:
    """Pick the crop centre, and also return what the localizer thought, for auditing.

    Returns `(used, localizer_opinion)`. Under `localizer_mode == "center_default"` the
    centred box wins unless the localizer is BOTH non-fallback AND at least
    `localizer_refine_min_confidence` confident. Under "localizer_primary" the old
    behaviour is restored, so the change is reversible from config alone.
    """
    opinion = localize_joint(img, params)
    if params.localizer_mode == "localizer_primary":
        return opinion, opinion
    centre = center_localization(img.shape, params)
    refined = (opinion.method != "fallback_center"
               and float(opinion.confidence) >= params.localizer_refine_min_confidence)
    return (opinion if refined else centre), opinion


def localize_joint(img: np.ndarray, params: PreprocessParams) -> Localization:
    """Locate the tibiofemoral joint on an already half-selected single-knee image.

    Classical and explainable (config localizer == "intensity_profile"): bone is
    bright, so Otsu on a smoothed copy gives a bone mask; the largest connected
    component is the limb; its row-wise mass profile has two maxima (distal femur,
    proximal tibia) separated by the dark joint space, and the joint line is the
    minimum between them. The column centre is the mask centroid near that row.

    `crop_confidence` is the relative prominence of that valley, in [0, 1]. When the
    mask is degenerate or the valley is not prominent enough the function returns the
    deterministic centred fallback with method == "fallback_center" and confidence 0;
    the fallback rate is a headline QA number reported by src.crop_qa.

    A learned detector (Colab, task T5) may replace this body but MUST return the same
    Localization contract on the same input.
    """
    assert img.ndim == 2, f"expected 2-D array, got ndim={img.ndim}"
    h, w = img.shape
    short = float(min(h, w))
    lo_side = params.min_crop_frac * short
    hi_side = params.max_crop_frac * short
    if h < 16 or w < 16:
        return _fallback_localization((h, w), params)

    scale = min(1.0, LOCALIZER_WORK_PX / float(max(h, w)))
    small = ndi.zoom(img, scale, order=1) if scale < 1.0 else img
    sh, sw = small.shape
    if sh < 16 or sw < 16:
        return _fallback_localization((h, w), params)

    sm = ndi.gaussian_filter(small, sigma=max(1.0, min(sh, sw) / 64.0))
    mask = sm > otsu_threshold(sm)
    frac = float(mask.mean())
    if frac < 0.02 or frac > 0.90:          # no bone found, or the whole field is "bone"
        return _fallback_localization((h, w), params)

    lab, n = ndi.label(mask)
    if n == 0:
        return _fallback_localization((h, w), params)
    sizes = np.bincount(lab.ravel())
    sizes[0] = 0
    comp = lab == int(np.argmax(sizes))

    rows = np.flatnonzero(comp.any(axis=1))
    cols = np.flatnonzero(comp.any(axis=0))
    if rows.size < 8 or cols.size < 4:
        return _fallback_localization((h, w), params)
    r0, r1 = int(rows[0]), int(rows[-1])
    height = r1 - r0 + 1

    profile = ndi.gaussian_filter1d(comp.sum(axis=1).astype(np.float64),
                                    sigma=max(1.0, height / 50.0))
    # Search only the middle half of the limb: the taper at the top/bottom of the
    # field is not a joint space.
    b0 = r0 + int(round(0.25 * height))
    b1 = r0 + int(round(0.75 * height))
    if b1 - b0 < 3:
        return _fallback_localization((h, w), params)
    j = b0 + int(np.argmin(profile[b0:b1 + 1]))

    up = profile[r0:j]
    dn = profile[j + 1:r1 + 1]
    if up.size == 0 or dn.size == 0:
        return _fallback_localization((h, w), params)
    peak_up, peak_dn = float(up.max()), float(dn.max())
    row_up = r0 + int(np.argmax(up))
    row_dn = j + 1 + int(np.argmax(dn))
    peak = min(peak_up, peak_dn)
    if peak <= 0:
        return _fallback_localization((h, w), params)
    confidence = float(np.clip((peak - float(profile[j])) / peak, 0.0, 1.0))
    if confidence < params.min_crop_confidence:
        return _fallback_localization((h, w), params)

    band = max(2, int(round(0.10 * height)))
    near = comp[max(r0, j - band):min(r1 + 1, j + band + 1), :]
    near_cols = np.flatnonzero(near.any(axis=0))
    if near_cols.size >= 2:
        col_small = float(near_cols.mean())
        knee_width = float(near_cols[-1] - near_cols[0] + 1)
    else:
        col_small = float(cols.mean())
        knee_width = float(cols[-1] - cols[0] + 1)

    # crop_margin_frac is padding on EACH edge as a fraction of the crop side, so the
    # anatomy occupies (1 - 2 * margin) of the output.
    base = max(knee_width, float(row_dn - row_up))
    side_small = base / max(1e-6, 1.0 - 2.0 * params.crop_margin_frac)

    # ndi.zoom rounds the output shape, so map back with the ACTUAL axis ratios.
    inv_r, inv_c = float(h) / float(sh), float(w) / float(sw)
    side = float(np.clip(side_small * 0.5 * (inv_r + inv_c), lo_side, hi_side))
    return Localization(row=float(j) * inv_r, col=col_small * inv_c, side=side,
                        confidence=confidence, method="intensity_profile")


# =============================================================================
# 5-8. Crop, orientation, marker masking, resize
# =============================================================================
def border_value(arr: np.ndarray, ring_frac: float = 0.02) -> float:
    """The image's own edge/background level (median of a thin border ring)."""
    h, w = arr.shape
    t = max(1, int(round(ring_frac * min(h, w))))
    ring = np.concatenate([arr[:t, :].ravel(), arr[-t:, :].ravel(),
                           arr[:, :t].ravel(), arr[:, -t:].ravel()])
    return float(np.median(ring)) if ring.size else 0.0


def square_crop(arr: np.ndarray, center_rc: tuple[float, float], side: float,
                pad_value: float | None = None) -> tuple[np.ndarray, float]:
    """Square crop centred on center_rc, padded with the image's own background value
    where it runs off the array. Never wraps.

    Returns (crop, padded_frac) where `padded_frac` in [0, 1] is the fraction of the
    RETURNED crop that is invented padding rather than source pixels. Protocol section
    13 requires the masked-pixel percentage to be recorded and used for exclusion, and
    padding is masked pixels by another name: it carries no anatomy, only the film's own
    background level. `finalize_image` folds this into `masked_pct`.
    """
    assert arr.ndim == 2, f"expected 2-D array, got ndim={arr.ndim}"
    h, w = arr.shape
    n = max(2, int(round(float(side))))
    r, c = center_rc
    r0 = int(round(r - n / 2.0))
    c0 = int(round(c - n / 2.0))
    if pad_value is None:
        pad_value = border_value(arr)
    out = np.full((n, n), float(pad_value), dtype=np.float32)
    sr0, sc0 = max(0, r0), max(0, c0)
    sr1, sc1 = min(h, r0 + n), min(w, c0 + n)
    if sr1 > sr0 and sc1 > sc0:
        out[sr0 - r0:sr1 - r0, sc0 - c0:sc1 - c0] = arr[sr0:sr1, sc0:sc1]
        covered = float(sr1 - sr0) * float(sc1 - sc0)
    else:
        covered = 0.0
    padded_frac = float(np.clip(1.0 - covered / float(n * n), 0.0, 1.0))
    return out, padded_frac


def standardize_orientation(crop: np.ndarray, contra_side: str,
                            standardize_to_left: bool) -> tuple[np.ndarray, str, bool]:
    """Mirror right knees so every output reads as a LEFT knee.

    Returns (array, orientation, mirrored) with orientation in {"left", "right"}
    describing how the returned crop READS, not the patient's anatomy.
    """
    side = str(contra_side).upper()
    assert side in ("L", "R"), f"contra_side must be L or R, got {contra_side!r}"
    if standardize_to_left and side == "R":
        return np.ascontiguousarray(crop[:, ::-1]), "left", True
    return crop, ("left" if side == "L" else "right"), False


def mask_borders(img: np.ndarray, mask_border_frac: float, fill: float = 0.0) -> np.ndarray:
    """Blank `mask_border_frac` of every edge.

    Burned-in L/R markers and technique text sit at the film margins, so this is a
    blunt but fully auditable guard: it does not detect anything, it unconditionally
    destroys a fixed frame. The RESIDUAL risk — a marker projected inboard of the
    frame — is exactly what the src.crop_qa visual gate exists to catch.
    """
    out = img.copy()
    h, w = out.shape
    t_r = int(round(float(mask_border_frac) * h))
    t_c = int(round(float(mask_border_frac) * w))
    if t_r > 0:
        out[:t_r, :] = fill
        out[h - t_r:, :] = fill
    if t_c > 0:
        out[:, :t_c] = fill
        out[:, w - t_c:] = fill
    return out


def to_uint8(arr: np.ndarray) -> np.ndarray:
    """[0, 1] float -> uint8, deterministic rounding."""
    return np.clip(np.rint(np.clip(arr, 0.0, 1.0) * 255.0), 0, 255).astype(np.uint8)


def border_band_fraction(out_size: int, mask_border_frac: float) -> float:
    """Fraction of an out_size square destroyed by `mask_borders`.

    Uses the SAME integer band width mask_borders uses, so the number reported is the
    number actually blanked. At out_size 512 and mask_border_frac 0.06 the band is
    round(0.06*512) = 31 px per edge and the fraction is 1 - (450/512)^2 = 0.227524, 22.75%.
    """
    n = int(out_size)
    t = int(round(float(mask_border_frac) * n))
    inner = max(0, n - 2 * t)
    return float(np.clip(1.0 - (inner * inner) / float(n * n), 0.0, 1.0))


def finalize_image(crop: np.ndarray, out_size: int, mask_border_frac: float,
                   padded_frac: float = 0.0) -> tuple[np.ndarray, float]:
    """Resize the square crop to out_size, mask the border, and report `masked_pct`.

    Masking runs AFTER the resize (not in the numbered pipeline order) on purpose: a
    resize filter mixes masked and unmasked pixels at the band boundary, which can
    bleed a bright marker back INSIDE the frame. Masking last guarantees the band is
    exactly round(mask_border_frac * out_size) px of a constant value on every edge.

    PROTOCOL SECTION 13 — "Record the percentage of masked pixels and exclude crops with
    excessive masking or failed localization." The returned `masked_pct` (a FRACTION in
    [0, 1], stored in the sidecar column `masked_pct`) is

        border_band_fraction(out_size, mask_border_frac) + padded_frac

    i.e. the fixed border frame the pipeline destroys plus the out-of-bounds padding
    `square_crop` invented, clipped to 1.0. The sum is deliberately CONSERVATIVE: thin
    padding lies inside the border band and is therefore double-counted, so `masked_pct`
    is an upper bound on the truly-blank area and the exclusion rule errs toward
    dropping a marginal crop rather than training on one.
    """
    u8 = to_uint8(crop)
    img = Image.fromarray(u8, mode="L").resize((int(out_size), int(out_size)),
                                               Image.Resampling.LANCZOS)
    out = mask_borders(np.asarray(img), mask_border_frac, fill=0)
    masked_pct = float(np.clip(border_band_fraction(out_size, mask_border_frac)
                               + float(padded_frac), 0.0, 1.0))
    return out, masked_pct


def encode_image(u8: np.ndarray, image_format: str = "png") -> bytes:
    fmt = str(image_format).lower()
    assert fmt == "png", f"only lossless png is allowed, got {image_format!r}"
    buf = io.BytesIO()
    Image.fromarray(u8, mode="L").save(buf, format="PNG", optimize=False,
                                       compress_level=PNG_COMPRESS_LEVEL)
    return buf.getvalue()


# =============================================================================
# The whole per-image crop pipeline (pure: array in, array + CropSpec out)
# =============================================================================
def crop_stages(arr: np.ndarray, *, view: str, laterality: str, contra_side: str,
                horizontal_flip: int, params: PreprocessParams) -> dict:
    """The full crop pipeline, returning EVERY intermediate src.crop_qa needs to render.

    Steps: flip correction -> half-select (BILATERAL frontals only) -> joint
    localization -> square crop -> orientation standardization -> resize -> border mask
    -> protocol-section-13 masked-pixel accounting.

    For unilateral frontals and for lateral/sunrise films the whole image is already
    the contralateral knee, so half-select is skipped; `laterality == contra_side` is
    asserted instead and a violation raises PreprocessError("laterality_mismatch").

    Returns a dict:
        film          flip-CORRECTED full film, float [0,1], NOT mirrored — what
                      src.crop_qa panel A must show
        half_bounds   (c0, c1) columns of `film` that were kept, or None when the whole
                      film is the contralateral knee
        premirror     final uint8 crop BEFORE standardize_orientation mirrors it — what
                      src.crop_qa panel B must show, because the mirror is exactly what
                      destroys the reviewer's left/right cue
        image         the final uint8 crop written to the shard
        spec          CropSpec (includes masked_pct)
        reject_reason None, or the protocol-section-13 reason this crop must NOT be
                      written ("excessive_masking" | "localization_failed")

    Geometry errors are RETURNED, not raised, so the QA gate can still render a rejected
    crop and show a reviewer why it was dropped. `crop_contralateral_knee` raises them.
    """
    lat = str(laterality).upper()
    side = str(contra_side).upper()
    if side not in ("L", "R"):
        raise PreprocessError("contra_side_unresolved", side)

    arr, flip_applied = apply_flip_correction(arr, horizontal_flip,
                                              params.apply_horizontal_flip_correction)
    # The array now obeys the display convention iff it was never flipped OR we just
    # un-flipped it; otherwise select_contralateral_half must account for the flag itself.
    flip_corrected = flip_applied or int(horizontal_flip or 0) != 1
    if lat == "B":
        half, half_name = select_contralateral_half(
            arr, side, horizontal_flip,
            convention=params.bilateral_display_convention,
            flip_corrected=flip_corrected,
            inset_frac=params.half_inset_frac)
        half_bounds = half_column_bounds(arr.shape[1], half_name, params.half_inset_frac)
    elif lat in ("L", "R"):
        if lat != side:
            raise PreprocessError("laterality_mismatch", f"laterality={lat} contra_side={side}")
        half, half_name, half_bounds = arr, "none", None
    else:
        raise PreprocessError("laterality_unresolved", lat)

    loc, loc_opinion = choose_localization(half, params)
    crop, padded_frac = square_crop(half, (loc.row, loc.col), loc.side)
    premirror, masked_pct = finalize_image(crop, params.out_size, params.mask_border_frac, padded_frac)
    # Burned-in markers that survived the border band (protocol section 13, non-negotiable #1).
    # Marker pixels ARE masked pixels, so they count toward masked_pct exactly as the protocol
    # defines it ("record the percentage of masked pixels").
    premirror, n_markers_masked, marker_frac = mask_burned_in_markers(premirror, params)
    masked_pct = float(min(1.0, masked_pct + marker_frac))
    # Mirror the FINISHED premirror image rather than re-deriving the final crop from the
    # unmirrored array. Resize, border mask and marker masking all commute with a left-right
    # flip, so this is equivalent — but running the marker detector once instead of twice keeps
    # the two images EXACTLY equivariant (a component-size tie can otherwise resolve differently
    # on the mirrored copy) and halves the work. The QA sheet relies on that equivalence.
    _, orientation, mirrored = standardize_orientation(crop, side, params.standardize_to_left)
    out = np.ascontiguousarray(premirror[:, ::-1]) if mirrored else premirror.copy()

    # ---- protocol section 13 exclusions --------------------------------------------
    # Under localizer_mode == "center_default" a centred box is a deliberate choice, so it
    # is NOT a failure and exclude_failed_localization is off; only genuine masking excess
    # drops an image. The old behaviour remains reachable from config alone.
    localization_failed = (loc.method == "fallback_center"
                           or float(loc.confidence) < params.min_crop_confidence)
    reject_reason: str | None = None
    if masked_pct > params.max_masked_pct:
        reject_reason = REASON_EXCESSIVE_MASKING
    elif params.exclude_failed_localization and localization_failed:
        reject_reason = REASON_LOCALIZATION_FAILED

    spec = CropSpec(view=view, contra_side=side, half_selected=half_name,
                    orientation=orientation, mirrored=mirrored,
                    crop_method=loc.method, crop_confidence=round(float(loc.confidence), 4),
                    masked_pct=round(float(masked_pct), 4))
    assert out.shape == (params.out_size, params.out_size), f"bad output shape {out.shape}"
    return {"film": arr, "half_bounds": half_bounds, "half_selected": half_name,
            "localization": loc, "localizer_opinion": loc_opinion,
            "padded_frac": float(padded_frac), "n_markers_masked": int(n_markers_masked),
            "marker_frac": float(marker_frac),
            "premirror": premirror, "image": out, "spec": spec,
            "reject_reason": reject_reason}


def crop_contralateral_knee(arr: np.ndarray, *, view: str, laterality: str, contra_side: str,
                            horizontal_flip: int, params: PreprocessParams) -> tuple[np.ndarray, CropSpec]:
    """Decoded DICOM array -> final out_size x out_size uint8 contralateral-knee crop.

    Thin wrapper over `crop_stages` that enforces the protocol-section-13 exclusions:
    a crop whose masked fraction exceeds `max_masked_pct` raises
    PreprocessError("excessive_masking"), and (when config
    `exclude_failed_localization` is set) a crop whose joint localization fell back to
    the deterministic centred box, or whose confidence is below `min_crop_confidence`,
    raises PreprocessError("localization_failed"). Both land in the failure report; a
    FAILED localization must never reach a shard.
    """
    st = crop_stages(arr, view=view, laterality=laterality, contra_side=contra_side,
                     horizontal_flip=horizontal_flip, params=params)
    spec: CropSpec = st["spec"]
    if st["reject_reason"] == REASON_EXCESSIVE_MASKING:
        raise PreprocessError(REASON_EXCESSIVE_MASKING,
                              f"masked_pct={spec.masked_pct:.4f} > max_masked_pct="
                              f"{params.max_masked_pct:.4f} (border band "
                              f"{border_band_fraction(params.out_size, params.mask_border_frac):.4f}"
                              f" + padding {st['padded_frac']:.4f})")
    if st["reject_reason"] == REASON_LOCALIZATION_FAILED:
        raise PreprocessError(REASON_LOCALIZATION_FAILED,
                              f"method={spec.crop_method} confidence={spec.crop_confidence:.4f} "
                              f"< min_crop_confidence={params.min_crop_confidence:.4f}")
    return st["image"], spec


# =============================================================================
# 9. Shard writing (stdlib tarfile; WebDataset shards are plain tars)
# =============================================================================
def uid_short(sop_uid: str) -> str:
    """Stable, collision-resistant short id for a SOPInstanceUID_anon.

    sha1 of the UID string, first 12 hex chars. Reproducible in any language, safe to
    print in outputs/ (no empi_anon), and dot-free so it is a legal WebDataset key part.
    """
    return hashlib.sha1(str(sop_uid).encode("utf-8")).hexdigest()[:UID_SHORT_LEN]


def sample_key(empi_anon: str, view: str, sop_uid: str) -> str:
    """WebDataset sample key: {empi_anon}_{view}_{uid_short}. Must contain no '.'."""
    key = KEY_TEMPLATE.format(empi_anon=str(empi_anon), view=str(view), uid_short=uid_short(sop_uid))
    assert "." not in key, f"sample key must not contain '.': {key!r}"
    return key


def _tar_footprint(nbytes: int) -> int:
    """Bytes a member of size nbytes occupies in a tar (512 header + padded payload)."""
    return 512 + ((int(nbytes) + 511) // 512) * 512


class ShardWriter:
    """Writes WebDataset shards for ONE split. Never mixes splits in a tar.

    All members of a sample share the basename `key` and are written back-to-back, so
    they are CONTIGUOUS in the tar as WebDataset requires.
    """

    def __init__(self, out_dir: Path, split: str, name_pattern: str, max_shard_mb: float):
        self.out_dir = Path(out_dir)
        self.out_dir.mkdir(parents=True, exist_ok=True)
        self.split = str(split)
        self.name_pattern = str(name_pattern)
        self.max_bytes = int(float(max_shard_mb) * 1024 * 1024)
        self.index = 0
        self.shards: list[str] = []
        self._tar: tarfile.TarFile | None = None
        self._bytes = 0
        self._n_in_shard = 0
        self.n_samples = 0

    @property
    def current_shard(self) -> str:
        return self.name_pattern.format(split=self.split, index=self.index)

    def _open(self) -> None:
        if self._tar is None:
            self._tar = tarfile.open(self.out_dir / self.current_shard, "w")
            self._bytes = 0
            self._n_in_shard = 0

    def _rotate(self) -> None:
        if self._tar is not None:
            self._tar.close()
            self.shards.append(self.current_shard)
            self._tar = None
            self.index += 1

    def write(self, key: str, members: list[tuple[str, bytes]]) -> str:
        """Write one sample. `members` is [(extension, payload), ...]; returns the shard name."""
        assert members, "a sample needs at least one member"
        size = sum(_tar_footprint(len(p)) for _, p in members)
        if self._tar is not None and self._n_in_shard > 0 and self._bytes + size > self.max_bytes:
            self._rotate()
        self._open()
        assert self._tar is not None
        for ext, payload in members:
            name = f"{key}.{ext}"
            info = tarfile.TarInfo(name=name)
            info.size = len(payload)
            info.mtime = 0                      # deterministic shards across re-runs
            info.mode = 0o644
            self._tar.addfile(info, io.BytesIO(payload))
        self._bytes += size
        self._n_in_shard += 1
        self.n_samples += 1
        return self.current_shard

    def close(self) -> None:
        if self._tar is not None:
            self._tar.close()
            self.shards.append(self.current_shard)
            self._tar = None


# =============================================================================
# Manifest assembly
# =============================================================================
# Regression anchors for build_manifest, VERIFIED against derived-data/cohort on
# 2026-07-24. The whole crop pipeline is downstream of this join, so a silent change in
# any input parquet (a re-run cohort build, a different split file, an upstream MRKR
# refresh) must fail HERE and loudly rather than quietly re-shape the training set.
MANIFEST_REGRESSION = {
    "n_rows_kept": 6090,            # 6,122 selected images - 32 'E'/'I' rows
    "n_dropped_views": 32,
    "n_patients": 3709,
    "n_frontal": 4269,
    "n_frontal_bilateral": 4075,    # laterality == 'B' -> needs the half-select
    "n_frontal_unilateral": 194,
    "n_lateral": 1659,
    "n_sunrise": 162,
    "n_horizontal_flip": 287,
    "n_inverted": 1476,
    "by_split": {"train": 4270, "val": 602, "test": 1218},
}


def build_manifest(cfg, log: logging.Logger | None = None) -> pd.DataFrame:
    """The image-grain work list: selected_study_images x final_cohort x patient_splits
    x image.parquet flags, restricted to config views_kept.

    Ends with the MANIFEST_REGRESSION assertions (see above) plus the two invariants the
    crop logic depends on: every kept NON-frontal row and every kept UNILATERAL frontal
    row must already have `laterality == contra_side`, because those images skip the
    half-select entirely and are cropped whole."""
    coh = cfg.path(cfg["paths"]["cohort_dir"])
    view_map = cfg["image"]["view_map"]
    views_kept = list(cfg["preprocess"]["views_kept"])

    img = pd.read_parquet(coh / "selected_study_images.parquet")
    fc = pd.read_parquet(coh / "final_cohort.parquet")[
        ["empi_anon", "StudyInstanceUID_anon", "index_side", "contra_side", "side_source",
         "n_concordant_signals", "event_indicator", "time_from_landmark", "view_set", "tier_name"]]
    sp = pd.read_parquet(coh / "patient_splits.parquet")[["empi_anon", "split"]]

    man = img.merge(fc, on=["empi_anon", "StudyInstanceUID_anon"], how="inner")
    man = man.merge(sp, on="empi_anon", how="left")
    assert man["split"].notna().all(), "some manifest images have no split assignment"

    flags = pd.read_parquet(cfg.parquet_path("image"),
                            columns=["SOPInstanceUID_anon", "horizontal_flip", "inverted"])
    man = man.merge(flags, on="SOPInstanceUID_anon", how="left")
    man["horizontal_flip"] = man["horizontal_flip"].fillna(0).astype(int)
    man["inverted"] = man["inverted"].fillna(0).astype(int)

    man["view"] = man["view_position"].map(view_map)
    n_all = len(man)
    man = man[man["view"].isin(views_kept)].reset_index(drop=True)
    if log is not None:
        log.info("manifest: %d image rows (%d patients); dropped %d rows outside views_kept=%s",
                 len(man), man["empi_anon"].nunique(), n_all - len(man), views_kept)
    assert man["SOPInstanceUID_anon"].is_unique, "duplicate SOPInstanceUID_anon in the manifest"

    _assert_manifest_regression(man, n_all, log)
    return man


def _assert_manifest_regression(man: pd.DataFrame, n_all: int,
                                log: logging.Logger | None = None) -> None:
    """Lock the verified manifest composition (see MANIFEST_REGRESSION)."""
    R = MANIFEST_REGRESSION
    vc = man["view"].value_counts().to_dict()
    frontal = man[man["view"] == "frontal"]
    bilat = frontal[frontal["laterality"] == "B"]
    uni_frontal = frontal[frontal["laterality"] != "B"]
    nonfrontal = man[man["view"] != "frontal"]
    by_split = man["split"].value_counts().to_dict()

    assert len(man) == R["n_rows_kept"], \
        f"manifest kept {len(man)} rows, expected {R['n_rows_kept']}"
    assert n_all - len(man) == R["n_dropped_views"], \
        f"dropped {n_all - len(man)} non-kept-view rows, expected {R['n_dropped_views']}"
    assert man["empi_anon"].nunique() == R["n_patients"], \
        f"manifest covers {man['empi_anon'].nunique()} patients, expected {R['n_patients']}"
    assert int(vc.get("frontal", 0)) == R["n_frontal"], f"frontal={vc.get('frontal')} != {R['n_frontal']}"
    assert int(vc.get("lateral", 0)) == R["n_lateral"], f"lateral={vc.get('lateral')} != {R['n_lateral']}"
    assert int(vc.get("sunrise", 0)) == R["n_sunrise"], f"sunrise={vc.get('sunrise')} != {R['n_sunrise']}"
    assert len(bilat) == R["n_frontal_bilateral"], \
        f"bilateral 'B' frontals={len(bilat)} != {R['n_frontal_bilateral']}"
    assert len(uni_frontal) == R["n_frontal_unilateral"], \
        f"unilateral frontals={len(uni_frontal)} != {R['n_frontal_unilateral']}"
    assert int((man["horizontal_flip"] == 1).sum()) == R["n_horizontal_flip"], \
        f"horizontal_flip==1 on {int((man['horizontal_flip'] == 1).sum())} != {R['n_horizontal_flip']}"
    assert int((man["inverted"] == 1).sum()) == R["n_inverted"], \
        f"inverted==1 on {int((man['inverted'] == 1).sum())} != {R['n_inverted']}"
    for split, n in R["by_split"].items():
        assert int(by_split.get(split, 0)) == n, \
            f"split {split} has {by_split.get(split, 0)} kept rows, expected {n}"

    # The half-select is applied ONLY to bilateral frontals. Everything else is cropped
    # whole, so its manifest laterality MUST already be the contralateral side — if that
    # ever stops holding, whole index-knee films would be written to the shards.
    bad_nf = int((nonfrontal["laterality"] != nonfrontal["contra_side"]).sum())
    bad_uf = int((uni_frontal["laterality"] != uni_frontal["contra_side"]).sum())
    assert bad_nf == 0, f"{bad_nf} kept non-frontal rows have laterality != contra_side"
    assert bad_uf == 0, f"{bad_uf} kept unilateral frontal rows have laterality != contra_side"
    if log is not None:
        log.info("manifest regression OK: %d rows / %d patients; frontal %d (B %d + uni %d), "
                 "lateral %d, sunrise %d; hflip==1 %d; splits %s",
                 len(man), man["empi_anon"].nunique(), R["n_frontal"], R["n_frontal_bilateral"],
                 R["n_frontal_unilateral"], R["n_lateral"], R["n_sunrise"],
                 R["n_horizontal_flip"], R["by_split"])


def view_masks(rows: pd.DataFrame, views_kept: list[str]) -> pd.DataFrame:
    """Per-patient missing-view mask: which of frontal/lateral/sunrise the patient has."""
    out = rows.groupby("empi_anon")["view"].agg(set).rename("views").reset_index()
    for v in views_kept:
        out[f"has_{v}"] = out["views"].apply(lambda s, v=v: v in s)
    out["n_views"] = out["views"].apply(len).astype(int)
    return out.drop(columns=["views"])


# =============================================================================
# Driver
# =============================================================================
def _fail_row(reason: str, row: pd.Series, detail: str = "") -> dict:
    """Failure records carry the sop-uid-short, NEVER empi_anon (outputs/ is not ignored)."""
    return {"reason": reason, "view": row.get("view", ""), "contra_side": row.get("contra_side", ""),
            "split": row.get("split", ""), "laterality": row.get("laterality", ""),
            "sop_uid_short": uid_short(row["SOPInstanceUID_anon"]), "detail": detail}


def assert_out_dir_is_outside_repo(out_dir: Path) -> None:
    """Refuse to write shards anywhere inside this repository.

    DATA HYGIENE, safety-critical: the shard sidecar carries `empi_anon` and the FULL
    SOPInstanceUID_anon for every image, and each sample's .json member repeats them.
    `--out-dir outputs/shards` would therefore drop patient identifiers straight into a
    tracked directory. derived-data/ and metadata-files/ are git-ignored, but shards are
    tens of GB and do not belong in the project tree at all — Drive or a scratch disk is
    the right destination. Raises ValueError with the fix spelled out.
    """
    resolved = Path(out_dir).expanduser().resolve()
    root = Path(PROJECT_ROOT).resolve()
    if resolved == root or root in resolved.parents:
        raise ValueError(
            f"--out-dir {resolved} is INSIDE the repository ({root}). The shard sidecar and "
            f"every sample .json carry empi_anon and full SOP UIDs, so writing them there would "
            f"put patient identifiers in a tracked path. Point --out-dir at a location outside "
            f"the project (a Drive folder, an external disk, or a scratch directory).")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description="DICOM -> contralateral-knee crop -> WebDataset shards (torch-free).")
    ap.add_argument("--config", default="config/feasibility.yaml")
    ap.add_argument("--dicom-root", required=True, help="root holding the transferred DICOM tree")
    ap.add_argument("--out-dir", default=None, help="directory the .tar shards are written to")
    ap.add_argument("--splits", default="train,val",
                    help="comma-separated splits to process; the sealed test split is EXCLUDED "
                         "by default and additionally requires --include-test")
    ap.add_argument("--include-test", action="store_true",
                    help="unseal the LOCKED test split (non-negotiable #4); logged loudly")
    ap.add_argument("--limit", type=int, default=None, help="process at most N images (smoke test)")
    ap.add_argument("--dry-run", action="store_true",
                    help="walk the manifest and report what WOULD be processed; reads no pixels")
    args = ap.parse_args(argv)

    cfg = load_config(args.config)
    log = setup_logging(cfg.path(cfg["paths"]["run_log"]))

    # ---- data-hygiene gate, checked FIRST so a bad --out-dir fails in milliseconds ----
    if args.out_dir:
        try:
            assert_out_dir_is_outside_repo(Path(args.out_dir).expanduser())
        except ValueError as exc:
            log.error("%s", exc)
            return 2

    # ---- input gate: a missing or empty DICOM root exits cleanly, no traceback ----
    dicom_root = Path(args.dicom_root).expanduser()
    if not dicom_root.exists() or not dicom_root.is_dir():
        log.error("DICOM root not found: %s", dicom_root)
        log.error("Nothing to preprocess. Transfer the DICOMs first (Track B: src.make_globus_batch "
                  "-> globus transfer), then re-run with --dicom-root pointing at that tree.")
        return 2
    suffix = str(cfg["transfer"]["dicom_suffix"])
    has_any = next(dicom_root.rglob(f"*{suffix}"), None)
    if has_any is None:
        log.error("DICOM root is EMPTY (no '*%s' under %s)", suffix, dicom_root)
        log.error("Nothing to preprocess. Transfer the DICOMs first (Track B: src.make_globus_batch "
                  "-> globus transfer), then re-run with --dicom-root pointing at that tree.")
        return 2

    splits = [s.strip() for s in str(args.splits).split(",") if s.strip()]
    assert splits, "--splits resolved to an empty list"
    bad = [s for s in splits if s not in ("train", "val", "test")]
    if bad:
        log.error("unknown split(s) %s; allowed: train, val, test", bad)
        return 2
    if "test" in splits and not args.include_test:
        log.error("REFUSING to process the LOCKED test split without --include-test "
                  "(success non-negotiable #4: the test set is read exactly once, after the "
                  "model, ensemble rule, thresholds and analysis script are frozen).")
        return 2
    if "test" in splits:
        log.warning("*** SEALED TEST SPLIT UNLOCKED via --include-test — this must happen ONCE, "
                    "after the model/ensemble/thresholds/analysis script are frozen and the crop "
                    "QA + laterality audit are signed off. ***")

    params = PreprocessParams.from_config(cfg)
    assert params.localizer == "intensity_profile", \
        f"only the intensity_profile localizer is implemented here, config says {params.localizer!r}"
    shard_cfg = cfg["preprocess"]["shards"]
    views_kept = list(cfg["preprocess"]["views_kept"])
    sidecar_columns = list(cfg["preprocess"]["sidecar_columns"])
    coh = cfg.path(cfg["paths"]["cohort_dir"])

    man = build_manifest(cfg, log)

    # The per-patient missing-view mask is a property of the COHORT, not of this run, so
    # it is computed from the FULL manifest BEFORE --splits/--limit narrow the work list.
    # Deriving it from a truncated work list would report n_views=1 for a patient whose
    # lateral and sunrise films simply were not scheduled, and that wrong mask would be
    # written into the shard the model reads.
    masks = view_masks(man, views_kept).set_index("empi_anon")

    work = man[man["split"].isin(splits)].sort_values(
        ["empi_anon", "view", "SOPInstanceUID_anon"], kind="mergesort").reset_index(drop=True)
    if args.limit is not None:
        work = work.head(int(args.limit)).reset_index(drop=True)
        log.warning("--limit %d: processing only the first %d scheduled images. n_views in the "
                    "sidecar remains the FULL-cohort mask; n_views_written will be smaller.",
                    int(args.limit), len(work))

    log.info("scheduled %d images / %d patients for splits=%s (test %s)",
             len(work), work["empi_anon"].nunique(), splits,
             "INCLUDED" if "test" in splits else "SEALED")
    for s in splits:
        sub = work[work["split"] == s]
        log.info("  split %-5s images=%d patients=%d views=%s", s, len(sub),
                 sub["empi_anon"].nunique(), sub["view"].value_counts().to_dict())
    log.info("  bilateral 'B' frontals needing half-select: %d; unilateral/other: %d",
             int(((work["view"] == "frontal") & (work["laterality"] == "B")).sum()),
             int(((work["view"] != "frontal") | (work["laterality"] != "B")).sum()))
    log.info("  horizontal_flip==1: %d; manifest inverted==1: %d",
             int((work["horizontal_flip"] == 1).sum()), int((work["inverted"] == 1).sum()))

    if args.dry_run:
        missing = 0
        for p in work["dicom_path"]:
            if not (dicom_root / str(p)).exists():
                missing += 1
        log.info("DRY RUN: no pixels read. %d/%d scheduled files present under %s (%d missing).",
                 len(work) - missing, len(work), dicom_root, missing)
        log.info("DRY RUN: would write shards named '%s' (<= %s MB) with sidecar '%s'.",
                 shard_cfg["name_pattern"], shard_cfg["max_shard_mb"], shard_cfg["sidecar_csv"])
        return 0

    if not args.out_dir:
        log.error("--out-dir is required unless --dry-run is used")
        return 2
    out_dir = Path(args.out_dir).expanduser()
    try:
        assert_out_dir_is_outside_repo(out_dir)
    except ValueError as exc:
        log.error("%s", exc)
        return 2
    out_dir.mkdir(parents=True, exist_ok=True)

    log.info("normalization: PER IMAGE robust clip at percentiles %s + min-max to [0,1]. "
             "No statistic is pooled across images, so nothing can leak across splits "
             "(non-negotiable #2) and nothing is persisted.", list(params.clip_percentiles))

    # A shorter re-run leaves higher-index shards from a previous, longer run behind; a
    # WebDataset glob would silently pick them up alongside the new ones.
    stale = sorted(p.name for s in splits for p in out_dir.glob(f"{s}-*.tar"))
    if stale:
        log.warning("%d pre-existing shard(s) in %s will be overwritten or ORPHANED: %s — delete "
                    "them before training if this run writes fewer shards", len(stale), out_dir,
                    ", ".join(stale[:10]) + (" ..." if len(stale) > 10 else ""))

    writers = {s: ShardWriter(out_dir, s, shard_cfg["name_pattern"], shard_cfg["max_shard_mb"])
               for s in splits}
    rows: list[dict] = []
    failures: list[dict] = []
    n_inverted_disagree = 0
    n_modality_lut_error = 0
    n_voi_lut_error = 0
    lut_error_examples: list[str] = []
    t0 = time.time()

    for i, row in enumerate(work.itertuples(index=False)):
        r = pd.Series(row._asdict())
        path = dicom_root / str(r["dicom_path"])
        # EVERYTHING per-image lives inside this try, key and record construction
        # included: a malformed time_from_landmark or empi_anon must route ONE image to
        # the failure report, not abort a 6,090-image run at image 5,000.
        try:
            if not path.exists():
                raise PreprocessError("file_not_found", "")
            arr, meta = read_dicom(path, params)
            if bool(meta["dicom_inverted"]) != bool(int(r["inverted"]) == 1):
                n_inverted_disagree += 1
            if meta.get("modality_lut_error"):
                n_modality_lut_error += 1
                if len(lut_error_examples) < 5:
                    lut_error_examples.append(f"modality_lut: {meta['modality_lut_error']}")
            if meta.get("voi_lut_error"):
                n_voi_lut_error += 1
                if len(lut_error_examples) < 5:
                    lut_error_examples.append(f"voi_lut: {meta['voi_lut_error']}")
            out, spec = crop_contralateral_knee(
                arr, view=str(r["view"]), laterality=str(r["laterality"]),
                contra_side=str(r["contra_side"]), horizontal_flip=int(r["horizontal_flip"]),
                params=params)

            key = sample_key(r["empi_anon"], spec.view, r["SOPInstanceUID_anon"])
            m = masks.loc[r["empi_anon"]]
            record = {
                "empi_anon": str(r["empi_anon"]),
                "sop_uid": str(r["SOPInstanceUID_anon"]),
                "view": spec.view,
                "contra_side": spec.contra_side,
                "split": str(r["split"]),
                "event_indicator": int(r["event_indicator"]),
                "time_from_landmark": int(r["time_from_landmark"]),
                "shard": "",
                "key": key,
                "crop_method": spec.crop_method,
                "crop_confidence": float(spec.crop_confidence),
                "masked_pct": float(spec.masked_pct),
                "sop_uid_short": uid_short(r["SOPInstanceUID_anon"]),
                "index_side": str(r["index_side"]),
                "laterality": str(r["laterality"]),
                "horizontal_flip": int(r["horizontal_flip"]),
                "inverted": int(r["inverted"]),
                "half_selected": spec.half_selected,
                "orientation": spec.orientation,
                "mirrored": bool(spec.mirrored),
                "out_size": int(params.out_size),
                **{f"has_{v}": bool(m[f"has_{v}"]) for v in views_kept},
                "n_views": int(m["n_views"]),
            }
            payload = {k: v for k, v in record.items() if k != "shard"}
            members = [(params.image_format, encode_image(out, params.image_format)),
                       ("json", json.dumps(payload, sort_keys=True).encode("utf-8"))]
        except PreprocessError as exc:
            failures.append(_fail_row(exc.reason, r, exc.detail))
            continue
        except Exception as exc:                      # never let one bad file kill the run
            failures.append(_fail_row("unexpected_error", r, f"{type(exc).__name__}: {exc}"))
            continue

        record["shard"] = writers[str(r["split"])].write(key, members)
        rows.append(record)
        if (i + 1) % 500 == 0:
            log.info("  processed %d/%d (%.1f img/s)", i + 1, len(work),
                     (i + 1) / max(1e-6, time.time() - t0))

    for wtr in writers.values():
        wtr.close()

    if not rows:
        log.error("no images were successfully processed (%d failures)", len(failures))
        _write_failures(cfg, failures, coh, log)
        return 1

    side = pd.DataFrame(rows)
    # Config-declared columns first, then the extras the training notebook needs.
    ordered = [c for c in sidecar_columns if c in side.columns]
    extras = [c for c in side.columns if c not in ordered]
    side = side[ordered + extras]

    written = view_masks(side, views_kept).set_index("empi_anon")
    n_written = written.rename(columns={f"has_{v}": f"w_{v}" for v in views_kept})
    side["n_views_written"] = side["empi_anon"].map(n_written["n_views"]).astype(int)
    drift = int((side["n_views"] != side["n_views_written"]).sum())
    if drift:
        log.warning("view-mask drift on %d rows: a scheduled view was lost to a decode failure; "
                    "group the sidecar by empi_anon for the authoritative mask", drift)
        failures.append({"reason": "view_mask_drift", "view": "", "contra_side": "", "split": "",
                         "laterality": "", "sop_uid_short": "", "detail": f"{drift} rows"})

    sidecar_path = out_dir / str(shard_cfg["sidecar_csv"])
    side.to_csv(sidecar_path, index=False)
    derived_copy = coh / f"preprocess_{shard_cfg['sidecar_csv']}"
    side.to_csv(derived_copy, index=False)

    fail_counts = pd.Series([f["reason"] for f in failures]).value_counts().to_dict() if failures else {}
    mp = side["masked_pct"].astype(float)
    run_json = {
        "out_dir": str(out_dir),
        "dicom_root": str(dicom_root),
        "splits": splits,
        "include_test": bool(args.include_test),
        "limit": int(args.limit) if args.limit is not None else None,
        "sidecar_csv": str(sidecar_path),
        "n_images_scheduled": int(len(work)),
        "n_images_written": int(len(side)),
        "n_patients_written": int(side["empi_anon"].nunique()),
        "n_failures": int(len(failures)),
        "failures_by_reason": {str(k): int(v) for k, v in fail_counts.items()},
        # protocol section 13 exclusions (these NEVER reach a shard)
        "n_excluded_excessive_masking": int(fail_counts.get(REASON_EXCESSIVE_MASKING, 0)),
        "n_excluded_localization_failed": int(fail_counts.get(REASON_LOCALIZATION_FAILED, 0)),
        "max_masked_pct": float(params.max_masked_pct),
        "border_band_fraction": round(border_band_fraction(params.out_size,
                                                           params.mask_border_frac), 4),
        "masked_pct": {
            "mean": round(float(mp.mean()), 4), "min": round(float(mp.min()), 4),
            "p50": round(float(mp.quantile(0.50)), 4), "p90": round(float(mp.quantile(0.90)), 4),
            "p99": round(float(mp.quantile(0.99)), 4), "max": round(float(mp.max()), 4),
            "n_gt_border_only": int((mp > border_band_fraction(params.out_size,
                                                               params.mask_border_frac) + 1e-9).sum()),
        },
        # fallback_rate is over WRITTEN crops and is 0 by construction while
        # exclude_failed_localization is on; localization_failure_rate is the real number.
        "fallback_rate": round(float((side["crop_method"] == "fallback_center").mean()), 4),
        "localization_failure_rate": round(
            float(fail_counts.get(REASON_LOCALIZATION_FAILED, 0))
            / max(1, len(side) + int(fail_counts.get(REASON_LOCALIZATION_FAILED, 0))), 4),
        # DICOM PhotometricInterpretation vs the manifest `inverted` flag. The DICOM tag
        # is authoritative; this count is a real QA number over the whole run.
        "n_inverted_disagree": int(n_inverted_disagree),
        "pct_inverted_disagree": round(100.0 * n_inverted_disagree / max(1, len(side)), 3),
        # LUT fallbacks are degradations, not failures — counted so they are never silent.
        "n_modality_lut_error": int(n_modality_lut_error),
        "n_voi_lut_error": int(n_voi_lut_error),
        "lut_error_examples": lut_error_examples,
        "shards": {s: writers[s].shards for s in splits},
        "params": {k: (list(v) if isinstance(v, tuple) else v) for k, v in asdict(params).items()},
        "written_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
    }
    (coh / "preprocess_run.json").write_text(json.dumps(run_json, indent=2))

    _write_failures(cfg, failures, coh, log)

    n_fb = int((side["crop_method"] == "fallback_center").sum())
    log.info("wrote %d samples / %d patients in %.1fs", len(side), side["empi_anon"].nunique(),
             time.time() - t0)
    for s in splits:
        sub = side[side["split"] == s]
        log.info("  split %-5s samples=%d shards=%d (%s)", s, len(sub), len(writers[s].shards),
                 ", ".join(writers[s].shards) or "none")
    n_loc_failed = int(fail_counts.get(REASON_LOCALIZATION_FAILED, 0))
    n_attempted = len(side) + n_loc_failed
    log.info("  crop_method fallback_center among WRITTEN crops: %d/%d (%.2f%%); mean "
             "crop_confidence %.3f. Localization-failure rate among crops that reached "
             "localization: %d/%d (%.2f%%) — with exclude_failed_localization=%s the written "
             "fallback count is 0 by construction, so the second number is the real one.",
             n_fb, len(side), 100.0 * n_fb / len(side), float(side["crop_confidence"].mean()),
             n_loc_failed, n_attempted, 100.0 * n_loc_failed / max(1, n_attempted),
             params.exclude_failed_localization)
    log.info("  half-select: %s", side["half_selected"].value_counts().to_dict())
    log.info("  orientation after standardize_to_left=%s: %s", params.standardize_to_left,
             side["orientation"].value_counts().to_dict())
    log.info("  masked_pct (protocol s13): mean %.4f  p50 %.4f  p90 %.4f  max %.4f  "
             "(border band alone %.4f, cap %.2f)", float(mp.mean()), float(mp.quantile(0.50)),
             float(mp.quantile(0.90)), float(mp.max()),
             border_band_fraction(params.out_size, params.mask_border_frac),
             params.max_masked_pct)
    log.info("  protocol s13 EXCLUSIONS (not written to any shard): excessive_masking=%d, "
             "localization_failed=%d (exclude_failed_localization=%s, min_crop_confidence=%.2f)",
             int(fail_counts.get(REASON_EXCESSIVE_MASKING, 0)),
             int(fail_counts.get(REASON_LOCALIZATION_FAILED, 0)),
             params.exclude_failed_localization, params.min_crop_confidence)
    log.info("  PhotometricInterpretation vs manifest 'inverted' disagreements: %d/%d (%.2f%%) "
             "(the DICOM tag is trusted; the manifest flag is reported only)",
             n_inverted_disagree, len(side), 100.0 * n_inverted_disagree / max(1, len(side)))
    if n_modality_lut_error or n_voi_lut_error:
        log.warning("  LUT fallbacks: modality-LUT %d, VOI-LUT %d (image kept, rescaled pixels "
                    "used). Examples: %s", n_modality_lut_error, n_voi_lut_error,
                    "; ".join(lut_error_examples) or "none")
    else:
        log.info("  LUT fallbacks: modality-LUT 0, VOI-LUT 0")
    log.info("  failures: %d %s", len(failures), fail_counts if failures else "{}")
    log.info("sidecar -> %s (copy: %s); run record -> %s", sidecar_path, derived_copy,
             coh / "preprocess_run.json")
    log.info("NEXT: python3 -m src.crop_qa  — training is BLOCKED until the crop QA sheet is signed.")
    return 0


def _write_failures(cfg, failures: list[dict], cohort_dir: Path, log: logging.Logger) -> None:
    """Failure reporting, split by data-hygiene tier.

    outputs/ is NOT git-ignored, so the configured fail_report_csv holds COUNTS BY
    REASON only (reason x view x contra_side x split). The row-level detail, keyed by
    sop_uid_short (never empi_anon, never a path), goes to git-ignored derived-data/.
    """
    cols = ["reason", "view", "contra_side", "split", "laterality", "sop_uid_short", "detail"]
    df = pd.DataFrame(failures, columns=cols) if failures else pd.DataFrame(columns=cols)

    path = cfg.path(cfg["preprocess"]["fail_report_csv"])
    path.parent.mkdir(parents=True, exist_ok=True)
    if len(df):
        agg = (df.groupby(["reason", "view", "contra_side", "split"], dropna=False)
                 .size().rename("n_images").reset_index()
                 .sort_values(["n_images", "reason"], ascending=[False, True]))
    else:
        agg = pd.DataFrame(columns=["reason", "view", "contra_side", "split", "n_images"])
    agg.to_csv(path, index=False)

    detail_path = cohort_dir / "preprocess_failures_detail.csv"
    detail_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(detail_path, index=False)
    log.info("failure report -> %s (%d aggregate rows, counts only); detail -> %s (%d rows, "
             "sop_uid_short only)", path, len(agg), detail_path, len(df))


if __name__ == "__main__":
    raise SystemExit(main())
